# Generated by Django 5.2.17 on 2026-09-17 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_producto'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='codigo',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='costo_compra',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
