# Generated by Django 5.2.17 on 2026-09-21 21:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0004_producto_presentacion_producto_stock_minimo'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovimientoInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ENTRADA', 'Entrada'), ('SALIDA', 'Salida')], max_length=10)),
                ('motivo', models.CharField(choices=[('COMPRA', 'Compra'), ('VENTA', 'Venta'), ('AJUSTE', 'Ajuste de inventario'), ('MERMA', 'Merma / Pérdida'), ('DEVOLUCION', 'Devolución'), ('OTRO', 'Otro')], max_length=20)),
                ('cantidad', models.PositiveIntegerField()),
                ('stock_anterior', models.PositiveIntegerField()),
                ('stock_nuevo', models.PositiveIntegerField()),
                ('observacion', models.TextField(blank=True, null=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='productos.producto')),
            ],
        ),
    ]
